version: "3.7"

services:
  front:
    image: node:18 #contenedor con node 18
    ports: 
      - 3000:3000 #el privado lo redireccione al público
    volumes:
      - ./front:/usr/src #el directorio front me lo mete en usr/src
    depends_on:
      - back #depende del back es decir que no se lance el front hasta que el back no este levantado
    command: bash -c "cd /usr/src && npm run dev" # comando para ejecutar el front. Que se vaya a donde esta el front(/usr/src) y que ejecute con el comendo de la derecha
    environment: #variables de entorno
      - SSR_HOST=http://back:8000  #esta seria la de nuestro back creado
      - NEXT_PUBLIC_CSR_HOST=http://localhost:8000
  back:
    image: denoland/deno:1.32.1
    ports:
      - 8000:8000
    volumes:
      - ./back:/usr/src
    command: bash -c "cd /usr/src && deno task dev"
